### ISSUE TITLE
User module | LogInFeature

### ISSUE THREAD

**Issue by lakshmipriyasundarraj** [fssa-batch3/sec_a_lakshmipriya.suntharaj__corejava_project_2#2]
**User Story**

- As a user, I want to log in with my email and password.
- Correct credentials grant access to my account; incorrect ones display error messages.

**Task: Implement User Login**

- [ ]  Create Data Access Object (DAO) Layer for user login.
- [ ]  Implement Service Layer for user login functionality.
- [ ]  Write JUnit Test Cases to ensure the login process works correctly.
- [ ]  Verify that all test cases are passing successfully.

###DAO:
- [ ] findUserByEmail

###Service:
- [ ] loginUser()

###Test:

-TestLoginFeature
- [ ] testLoginSuccess()

Estimation: 6hours

**Flow chart**

```mermaid
graph TD
A[[Start]] --> B([Validate User])
B --> |Valid| C[(Retrieve User from Database)]
B --> |Invalid| E{{Validation Exception}}
C --> |User Not Found| F{{ServiceException}}
C --> |User Found| D([Check Password Match])
D --> |Returns User| I([Login Successful])
E --> G([Login Failed])
F --> G
D --> |Password Mismatch| G
G --> H[[End]]
I --> H
```
