### ISSUE TITLE
Recipe | ListRecipe

### ISSUE THREAD

**Issue by lakshmipriyasundarraj** [fssa-batch3/sec_a_lakshmipriya.suntharaj__corejava_project_2#4]
**User Story**
As an user, I want the ability to view a list of all the recipe  in the collection. The system should provide me with a list that includes details such as recipe names, description, incredients, steps, and the image url. This way, I can easily monitor and manage the recipe that are part of the collection.

**Task: Implement Design Listing for Architects**
- [ ]  Develop the Data Access Object (DAO) Layer for listing recipe.
- [ ]  Implement the Service Layer to handle the recipe listing .
- [ ]  Create JUnit Test Cases to ensure the correctness of the recipe listing functionality.
- [ ]  Verify that all test cases are passing successfully.

### ###DAO: 
- [ ] getAllRecipesByCategory()

### ###Service:
- [ ] listRecipesByCategory()

### ###Testcases:
-TestListRecipeFeature
- [ ] testReadRecipeFeature

Estimation: 6hours

``` mermaid
graph TD
A[[Start]] -->|User Initiates recipe Listing| B([Fetch recipe])
B -->|recipe Found| C([Display recipe List])
B -->|No recipe Found| D{{No recipe Available}}
C --> H[[End]]
D --> H

 ```
