### ISSUE TITLE
Recipe | UpdateRecipe

### ISSUE THREAD

**Issue by lakshmipriyasundarraj** [fssa-batch3/sec_a_lakshmipriya.suntharaj__corejava_project_2#5]
**User Story**

- As a user, I want to be able to update the details of a recipe in the collection. This includes modifying recipe names, description, ingredients, steps , and the image url By having the ability to update recipe information 

**Task: Implement Design Update**
- [ ]  Develop the Data Access Object (DAO) Layer for updating recipes.
- [ ]  Implement the Service Layer to handle the recipe update process for architects.
- [ ]  Create JUnit Test Cases to ensure the correctness of the recipe update functionality.
- [ ]  Verify that all test cases are passing successfully.
###DAO:
- [ ] updateRecipe()

###Service:
- [ ] editRecipe()

###TestCases:

- [ ] testUpdateRecipeSuccess()
- [ ] testUpdateRecipeInvalidData()

**Estimation: 6hours**

``` mermaid 
graph TD
A[[Start]] -->|user Initiates recipe Update| B([Select recipe to Update])
B -->|recipe Selected| C([recipe Design Details])
B -->|recipe Not Found| D{{recipe Not Found}}
C --> E([Update Successful])
D --> H[[End]]
E --> H




```
