### ISSUE TITLE
Recipe |  DeleteRecipe

### ISSUE THREAD

**Issue by lakshmipriyasundarraj** [fssa-batch3/sec_a_lakshmipriya.suntharaj__corejava_project_2#6]
**User Story**
As a user, I want to be able to delete one of my recipe from the collection. This way, I can easily manage and remove recipe that are no longer needed.

**Task: Implement Design Deletion for Architects**
- [ ]  Develop the Data Access Object (DAO) Layer for deleting recipes.
- [ ]  Implement the Service Layer to handle the recipe deletion process for architects.
- [ ]  Create JUnit Test Cases to ensure the correctness of the recipe deletion functionality.
- [ ]  Verify that all test cases are passing successfully.

###DAO: 
- [ ] deleteRecipe

###Service:
- [ ] deleteRecipe

###Testcases
- [ ] deleteRecipeFeature

Estimation: 6hours

``` mermaid 

graph TD
A[[Start]] -->|user Initiates recipe Deletion| B([Fetch Design to Delete])
B -->|recipe Found| C([Confirm Deletion])
C -->|Confirmed| E([Delete recipe])
E --> F[[End]]
C -->|Cancelled| G([Cancel Deletion])
G --> H[[End]]
B -->|No recipe Found| D{{Design Not Found}}
D --> H


```
